[package]
name = "opis"
version = "0.6.0"
edition = "2018"
license = "MIT"
description = "Opis is an arithmetic library for positive integers of any size written in Rust."
repository = "https://github.com/seg-software/rust-opis"
readme = "README.md"

[dependencies]
