[package]
name = "opis"
version = "4.1.0"
edition = "2021"
license = "MIT"
description = "Opis is an arithmetic library for integer numbers."
repository = "https://github.com/stelar-labs/opis-rs"
readme = "README.md"

[dependencies]
