[package]
name = "opis"
version = "3.0.7"
edition = "2018"
license = "MIT"
description = "Opis is an arithmetic library for integer numbers written in Rust."
repository = "https://github.com/stelar-software/rust-opis"
readme = "README.md"

[dependencies]
