[package]
name = "opis"
version = "6.0.0"
edition = "2021"
license = "MIT"
description = "Opis is a library for Number and Matrix Arithmetic."
repository = "https://github.com/stelar-labs/opis-rs"
readme = "README.md"

[dependencies]
